# Generated by Django 5.2.5 on 2025-08-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[("coffee", "Coffee"), ("tea", "Tea"), ("pastry", "Pastry")],
                default="coffee",
                max_length=20,
            ),
        ),
    ]
